
project_id = "bqscfculigcgantgdjat"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[[api.headers]]
name = "Access-Control-Allow-Origin"
value = "*"

[functions]
port = 54323

[db]
port = 54322

[studio]
port = 54324

[storage]
file_size_limit = 50000000
