// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqscfculigcgantgdjat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxc2NmY3VsaWdjZ2FudGdkamF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4ODA2MDAsImV4cCI6MjA2MjQ1NjYwMH0.cTcAdG4yjmqyJGOQ76yZRBNkPrLZvUEHJ__iQCDeODc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);